### ISSUE TITLE
Ensure latest version of style is used after slicer.org or download.slicer.org deployement

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#140]
Following the integration of https://github.com/Slicer/slicer.org/pull/136, I observed that the website needed a "hard refresh" to properly display the icon.

This is because the style was modified and we don't have "cache busting" mechanism in place. 

### Proposed solution

See https://murfitt.net/blog/cache-busting-with-jekyll

cc: @jamesobutler @lassoan @pieper

**Comment by pieper** [comment]
Personally I think this was a small enough issue and rare enough that we don't need to implement a special workaround.  We don't really plan on changing this content much.

**Comment by jamesobutler** [comment]
@jcfr was it "hard refreshed" based on https://github.com/Slicer/slicer.org/commit/02bb08e8ee675da195dec08ab79e02b66b6cb871? It currently doesn't seem to include changes from https://github.com/Slicer/slicer.org/commit/aa6ed1923be914dae5839db73e8966bfd4e85128 as the site currently looks like https://github.com/Slicer/slicer.org/pull/136#issuecomment-1031377116.

**Comment by jcfr** [comment]
If you look the bottom of the page, it includes the following:

![image](https://user-images.githubusercontent.com/219043/153095770-a48be675-0a37-426e-a68b-93d521494b89.png)

This means that the html is the correct one as it based of https://github.com/Slicer/slicer.org/commit/d5fd015

But as you correctly observe the style currently in the cache is the one being used, and this explained what you observe.
