### ISSUE TITLE
Display section at top of the page

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#17]
_Originally posted by @fedorov in https://github.com/Slicer/slicer.org/pull/16#issuecomment-665747948_

Comment based on preview of 2020.07.29 that was available at https://deploy-preview-16--slicer-org.netlify.app/ (https://github.com/Slicer/slicer.org/commit/0a1313b40ebc23ed2f8015b0676992fa2cffbc43)

> I also think it would be better if the page could be split into sections that could appear at the top of the page to facilitate navigation. Something like is done in this page: http://qiicr.org/dicom4miccai/ (see items in the top right that scroll to a position in the page).

As the user scroll, current section could be highlighted at the top:

![image](https://user-images.githubusercontent.com/219043/88825245-597e4080-d195-11ea-9881-358d76be44e5.png)

**Comment by jcfr** [comment]
During the design meeting with the community, it was discussed that the main landing page wouldn't have the section at the top. Only sub-page (commercial use, ... ) would display it.

**Comment by fedorov** [comment]
Just curious, when did that design meeting with the community happen?

**Comment by jcfr** [comment]
> Just curious, when did that design meeting with the community happen?

Note: Later this afternoon, I will summarize and post on discourse.

Thanks for sharing your concerns. I am realizing, that (1) I should have more proactively reach out to the community to build a stronger awareness of the on-going changes related to the landing page, (2) update the hangout agenda to explicitly indicate we would talk about the landing page redesign and (3) provide more opportunity for feedback.

There is still opportunity to address this, if you are available, I suggest you and @cpinter join tomorrow hangout so that we can all review the current status and progress toward a landing page we will be happy with.

### Background

For reference, here some more details:

The idea of re-designing the landing page was [first discussed](https://github.com/NA-MIC/ProjectWeek/blob/master/PW33_2020_GranCanaria/Breakouts/Slicer5/README.md#web-landing-page-for-slicerorg) during the project week in LasPalmas.

If I recall, it was discussed during one of the Slicer hangout of early April.

Then, following the hangout, I [updated](https://discourse.slicer.org/t/its-all-about-transitions-lets-talk-about-slicers-landing-page/113/43?u=jcfr) the existing thread by indicating the landing page redesign task has been added to the Kitware team design queue.

Then, during multiple follow-up hangout, we reviewed mock-ups on [June 16](https://discourse.slicer.org/t/2020-06-16-hangout/12047), shared a google doc to iterate on the textual content on [July 7](https://discourse.slicer.org/t/2020-07-07-hangout/12400)

Cc: @pieper @lassoan @cpinter @fedorov

**Comment by fedorov** [comment]
@jcfr thank you for the clarification. I didn't mean to ask as a criticism - I have not been participating in the Slicer meetings for  quite some time, so not surprising I fell behind. As I said, I was just curious.

Unfortunately, I have a conflict for tomorrow 10:30am meeting, otherwise I would try to join.

I do want to note, however, that the notes you referenced have the following statement:

> design similar to what is done on https://salt.slicer.org/ or https://jupyter.org would be ideal

Both of the designs mentioned do have section navigation header at top of the page.

I don't mean to derail the development - Slicer home page is overdue for redesign, and you guys are the ones doing the work. I just happened to notice the PR, and I thought feedback is solicited, so I added some comments.

Thank you for working on updating this content.

**Comment by jcfr** [comment]
> I do want to note, however, that the notes you referenced have the following statement:

Indeed, we initially had a banner ... but during the meeting we agreed to note have one by default.
I am now talking with  @faiza-a to show a banner, only after you start scrolling. 

> I thought feedback is solicited, so I added some comments.

Indeed, thanks for taking the time to review :pray:

**Comment by jcfr** [comment]
See https://github.com/Slicer/slicer.org/commit/09de8b210e555aea38a62d199391bb8cacfb3f74

Initially no navigation bar is displayed:

![image](https://user-images.githubusercontent.com/219043/89255812-a2e4ea80-d5f0-11ea-884b-4258cef4ad16.png)

After scrolling passed the "hero" section, it appears:

![image](https://user-images.githubusercontent.com/219043/89255951-066f1800-d5f1-11ea-9433-631854876d1c.png)

**Comment by faiza-a** [comment]
this is what i did intentionally. Coz we don't want any header on main page hero.
If you want to display the header on less scroll. we can change ('scroll > 500') this value in header.html 
if we set (scroll > 250) header will appear when half of hero section is passed.
If we want to have the header appearing all the time. just set (animated_navbar: false) in index.html
