### ISSUE TITLE
Updated Landing Page: Order of color between top-level line and button seems arbitrary

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#28]
![image](https://user-images.githubusercontent.com/219043/89058825-068bc100-d32e-11ea-8b68-314ae5145fb6.png)

**Comment by faiza-a** [comment]
Fixed in 6c04033

**Comment by jcfr** [comment]
@vovythevov  This addresses the issue you raised last week.

|  Old | New |
|----|-----|
|  ![image](https://user-images.githubusercontent.com/219043/89058825-068bc100-d32e-11ea-8b68-314ae5145fb6.png) | ![image](https://user-images.githubusercontent.com/219043/89215070-f70eb100-d595-11ea-8675-e203bc8c787e.png)|

**Comment by faiza-a** [comment]
I also tried buttons and hero border color sequence match the logo color sequence. (like in screenshot below) i wasnt very impressed with that. but if you like this version. i can keep this sequence.
<img width="1791" alt="Screen Shot 2020-08-03 at 1 59 15 PM" src="https://user-images.githubusercontent.com/61198087/89216330-30e0b700-d598-11ea-8fbe-9a245801a0ac.png">
