### ISSUE TITLE
Add follow-us section at bottom + Create 3DSlicerApp youtube brand account

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#32]
![image](https://user-images.githubusercontent.com/219043/89228023-d00fa980-d5ac-11ea-8f2b-627760dc73da.png)

* Twitter: https://twitter.com/3DSlicerApp
* Youtube: <s>https://www.youtube.com/results?search_query=%223d+slicer%22+OR+%223D+Slicer%22&sp=CAI%253D</s> https://www.youtube.com/channel/UCNNprn6jHt-ZgyTOdETdzWQ/playlists

**Comment by lassoan** [comment]
Instead of a search query, we should register a 3DSlicerApp user to youtube (we can then create playlists, etc.). @jcfr should I register it or you would prefer to do it?

**Comment by jcfr** [comment]
> we should register a 3DSlicerApp user to youtube

Like we need to create a brand account. On youtube this means creating a channel:
* https://support.google.com/accounts/answer/7001996?co=GENIE.Platform%3DDesktop&hl=en
* https://support.google.com/youtube/answer/1646861

**Comment by jcfr** [comment]
For future reference:

* https://www.youtube.com/channel_switcher
![image](https://user-images.githubusercontent.com/219043/89232036-917ded00-d5b4-11ea-9f8b-8feb1e582f89.png)

* Click on "create a new channel" named `3DSlicerApp`

* Here it is: https://www.youtube.com/channel/UCNNprn6jHt-ZgyTOdETdzWQ?guided_help_flow=3

**Comment by jcfr** [comment]
* Then, go to https://myaccount.google.com/brandaccounts:

![image](https://user-images.githubusercontent.com/219043/89232204-fa656500-d5b4-11ea-8d5c-ff87cba108c0.png)

* Manage Permissions

![image](https://user-images.githubusercontent.com/219043/89232246-0ea96200-d5b5-11ea-8652-7fe46b2696a4.png)

* Add users:

![image](https://user-images.githubusercontent.com/219043/89232284-1ff26e80-d5b5-11ea-9f2d-8515ef6484a0.png)

* All set:

![image](https://user-images.githubusercontent.com/219043/89232388-592ade80-d5b5-11ea-9ef6-7cb9c3d01b81.png)

**Comment by lassoan** [comment]
I remember we had a shared Slicer google account. Should I use that? I could not find username/password for it, but maybe I could look for it some more then I can find it.

**Comment by jcfr** [comment]
I invited you, @pieper and @sjh26  to the "3DSlicerApp" brand account, it will be easier to work with. 

> shared Slicer google account. Should I use that?

Is it associated with this account https://www.youtube.com/channel/UC11x1iQ7ydSIFYw4L6wveXg ? 

With yes, we should invite others to join the account and i will delete the one I just created.

Let me know

**Comment by lassoan** [comment]
There are two channels:
- https://www.youtube.com/channel/UC11x1iQ7ydSIFYw4L6wveXg (3D Slicer): contains mostly very old (4+ years old) videos
- https://www.youtube.com/channel/UCNNprn6jHt-ZgyTOdETdzWQ (3DSlicerApp): contains no videos

Can you confirm that the plan is to create new playlists for 3DSlicerApp account and leave the old 3D Slicer account as is (or maybe disable/hide/remove it)?

**Comment by jcfr** [comment]
Short answer: Yes

> and leave the old 3D Slicer account as is (or maybe disable/hide/remove it)?

To clarify, we do not have access to this account otherwise it would have make sense to consolidate.

I tentatively resurrected on very old email thread to try to find who manager it.

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/Slicer/slicer.org/commit/19633f5ce4d76ed4c2f254c56b802f6fa815eb6e

![image](https://user-images.githubusercontent.com/219043/89396002-0730a880-d6dc-11ea-9b0c-17bb14a60562.png)
