### ISSUE TITLE
Update "What is Slicer" section

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#35]
| Current | Proposed
|----|----|
| ![image](https://user-images.githubusercontent.com/219043/89239937-aebcb680-d5c8-11ea-8097-96ba343e9728.png)| ![image](https://user-images.githubusercontent.com/219043/89239910-977dc900-d5c8-11ea-9363-53b6bb1654da.png)|

Current:

```
<p>3D Slicer is a community supported open source software platform for medical image informatics, image processing, and three-dimensional visualization.<br> Built over two decades through support from the National Institutes of Health and a worldwide developer community. Slicer brings free, powerful cross-platform processing tools to physicians, researchers, and the general public.</p>
```

Proposed:

```
<ul><li><b>Software</b> application for visualization and analysis of medical image computing datasets<ul><li>Supports images, segmentations, surfaces, annotations, transformations, etc., in 2D, 3D, and 4D.</li><li>Visualization is available on desktop and in virtual reality.</li><li>Analysis includes segmentation, registration, and various quantifications.</li></ul></li>
  <li><b>Research</b> software platform, which allows researchers to quickly develop and evaluate new methods and distribute them to clinical users.</li>
<li><b>Product</b> development platform, which allows companies to quickly prototype and release products to users.</li></ul>
```

**Comment by jcfr** [comment]
I updated the section to be simpler by removing:
* Supports images, segmentations, surfaces, annotations, transformations, etc., in 2D, 3D, and 4D.
* Analysis includes segmentation, registration, and various quantifications.

It would be nice to include these in the feature list (see #19)

![image](https://user-images.githubusercontent.com/219043/89450404-7cc26600-d728-11ea-9d5f-1be6bb4fa567.png)

**Comment by jcfr** [comment]
@pieper  What do you think of this updated "What is Slicer" ?

**Comment by pieper** [comment]
How about:

* **Application software** to solve advanced medical image computing challenges
* **Development platform** to quickly develop and deploy custom solutions for research and commercial products
* **Community** of knowledgable users and developers working together to improve medical computing

**Comment by jcfr** [comment]
I like where this is going :pray: , I will wait to hear back from @lassoan also.

**Comment by fedorov** [comment]
Should it really be medical only? Also, I think the strength of Slicer is not just in solving advanced challenges, but also making it easy and quick to do non-advanced tasks that may be challenging to do using other means. How about something like

"to streamline common visualization tasks and support advanced image computing challenges, with the main focus on medical imaging"

**Comment by pieper** [comment]
Yes, maybe we should call it "a computing platform with deep roots in medical imaging".  Then it covers SlicerMorph and SlicerAstro too.

**Comment by lassoan** [comment]
Adding "with a focus on clinical and biomedical applications" and "free, open-source" and some minor word changes:

- **Desktop software** to solve advanced image computing challenges with a focus on clinical and biomedical applications
- **Development platform** to quickly build and deploy custom solutions for research and commercial products, using free, open-source software
- **Community** of knowledgeable users and developers working together to improve medical computing

**Comment by jcfr** [comment]
Closing.

We will review this during next week hangout: https://discourse.slicer.org/t/2020-08-11-hangout-w-project-week-discussion/12881
