### ISSUE TITLE
Add css class for hiding table header section

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#38]
Listing of product has been improved:

![image](https://user-images.githubusercontent.com/219043/89398867-a99e5b00-d6df-11ea-91a8-fa8eda07750e.png)

@faiza-a Would it be possible to had styling for hiding the `thead` element of selected tables? 

That way, it would render like this:

![image](https://user-images.githubusercontent.com/219043/89399242-30ebce80-d6e0-11ea-9faa-da3f87a7f9f4.png)

_Originally posted by @jcfr in https://github.com/Slicer/slicer.org/issues/33#issuecomment-669100013_

**Comment by faiza-a** [comment]
Fixed in 346fa49
