### ISSUE TITLE
Fix features section layout/spacing

### ISSUE THREAD

**Issue by faiza-a** [Slicer/slicer.org#40]
![Screen Shot 2020-08-05 at 3 38 37 PM](https://user-images.githubusercontent.com/61198087/89456352-c06d9d80-d731-11ea-8bda-707d33664e90.png)

**Comment by jcfr** [comment]
Closing. As of bb8a568500f370fc27d3fd5a09b685abe5bd6731, we have:



![image](https://user-images.githubusercontent.com/219043/89835954-bda8e900-db33-11ea-90ad-98da584b88b2.png)

![image](https://user-images.githubusercontent.com/219043/89835980-cac5d800-db33-11ea-91c9-c534849ae25f.png)
