### ISSUE TITLE
Fix header for mobile version

### ISSUE THREAD

**Issue by faiza-a** [Slicer/slicer.org#41]
![IMG_2135](https://user-images.githubusercontent.com/61198087/89456979-aaaca800-d732-11ea-9691-2320d7659734.jpg)

**Comment by jcfr** [comment]
As of bb8a568500f370fc27d3fd5a09b685abe5bd6731, the header is now properly rendered:

![image](https://user-images.githubusercontent.com/219043/89836067-fc3ea380-db33-11ea-8512-cc4e8d8d3124.png)

**Comment by jcfr** [comment]
But clicking on the icon:

![image](https://user-images.githubusercontent.com/219043/89836222-4758b680-db34-11ea-8eba-8575cf356a5b.png)

doesn't do anything.

Cc: @faiza-a

**Comment by faiza-a** [comment]
Fixed in 7382c96

**Comment by jcfr** [comment]
Closing. 

![image](https://user-images.githubusercontent.com/219043/90693674-3ea76500-e245-11ea-8408-bbcf95158be9.png)
