### ISSUE TITLE
Readability of forum button (white text on yellow)

### ISSUE THREAD

**Issue by pieper** [Slicer/slicer.org#42]
Showed the draft page to @ljod and she ❤️ s it!

Her first impression comment was that the Forum link was hard to read.  Not sure if there's a good fix for that, maybe different text colors for all the boxes?  (maybe black?)

**Comment by jcfr** [comment]
Thanks for the feedback :pray: 

In https://github.com/Slicer/slicer.org/commit/a19080b052a29028b41ab48dadc246ddbc6261b0, I reverted back lighter color. 

I am wondering **Option 1** would be better  ...

| Option 1 | Option 2 |
|----|----|
| ![image](https://user-images.githubusercontent.com/219043/89542776-20b21d00-d7ce-11ea-9266-57f5b0873ac2.png) |![image](https://user-images.githubusercontent.com/219043/89542680-fa8c7d00-d7cd-11ea-8a73-cf61a575f2e1.png)|


I would be curious to know what @faiza-a think.

**Comment by jcfr** [comment]
@pieper @ljod  Does Option1 look better ?

**Comment by pieper** [comment]
TBH I don't see any difference between the two options?

**Comment by ljod** [comment]
Yeah they look really similar

**Comment by jcfr** [comment]
It is very subtle.

Here some other options: 

Would "Experiment-1" or "Experiiment-3" work better ? 

|  | |
|------|----|
| Current | ![image](https://user-images.githubusercontent.com/219043/89556466-6cb98d80-d7df-11ea-82e9-fedaf26d3612.png) | 
| Experiment-1 |![image](https://user-images.githubusercontent.com/219043/89556219-0b91ba00-d7df-11ea-8027-56c2b1d416c0.png) |
| Experiment-2 | ![image](https://user-images.githubusercontent.com/219043/89556642-b1ddbf80-d7df-11ea-941e-2a1f0fb23fdd.png) |
| Experiment-3 | ![image](https://user-images.githubusercontent.com/219043/89557093-4c3e0300-d7e0-11ea-997f-72a891942cc3.png) |

**Comment by ljod** [comment]
I like current or experiment 3.

**Comment by jcfr** [comment]
Thanks for the feedback

@faiza-a Is this a reasonable approach:

```diff
diff --git a/_sass/classes.sass b/_sass/classes.sass
index a0e2951..21b6331 100644
--- a/_sass/classes.sass
+++ b/_sass/classes.sass
@@ -17,6 +17,7 @@
 .button
   transition: background .15s ease-in-out, color .15s ease-in-out
   border-width: 2px
+  font-weight: bold
   &:hover
     background-color: white
     border-width: 2px
```

**Comment by faiza-a** [comment]
I think  bright colors with light font is looking better (the current version)
light font is looking better than bold font in my opinion. and its going with overall theme.
I can try tweaking the yellow color so that the text 'forum' is a little more visible.

**Comment by jcfr** [comment]
Closing. As of 0de227038238128773e0e92476c0c6ab3e20bb43, we have:

![image](https://user-images.githubusercontent.com/219043/89835108-16778200-db32-11ea-9df4-f1e797b3671c.png)

Color has been tweaked. Re-open the issue if this still a concern.

|  | |
|------|----|
| Before | ![image](https://user-images.githubusercontent.com/219043/89556466-6cb98d80-d7df-11ea-82e9-fedaf26d3612.png) | 
| After |![image](https://user-images.githubusercontent.com/219043/89835188-432b9980-db32-11ea-89e8-bd7fa1cbeb74.png)|
