### ISSUE TITLE
Call Slicer an image computing platform in the hero section

### ISSUE THREAD

**Issue by pieper** [Slicer/slicer.org#43]
Following up on the discussion here: https://github.com/Slicer/slicer.org/issues/35#issuecomment-669479299

I think using the term "biomedical" in the big hero headline gives the wrong first impression.

How about the big text above the boxes: "3D Slicer image computing platform"

And below the boxes: "3D Slicer is a free, open source and multi-platform software package with roots in medical imaging."

**Comment by fedorov** [comment]
I like the suggestion overall, but not particularly excited about "with roots".

Maybe "with the primary focus on medical imaging" or something like that?

**Comment by pieper** [comment]
How about "widely used for medical, biomedical, and related imaging research"

**Comment by jcfr** [comment]
To be consistent with https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3466397/

```diff
- 3D Slicer biomedical image computing platform
+3D Slicer image computing platform
```

```diff
-3D Slicer is a free, open source and multi-platform software package.
+3D Slicer is a free, open source and multi-platform software package widely used for medical, biomedical, and related imaging research.
```

**Comment by jcfr** [comment]
Thanks for the feedback :pray: 

Closing. We will review this during next week hangout: https://discourse.slicer.org/t/2020-08-11-hangout-w-project-week-discussion/12881
