### ISSUE TITLE
Carousel Images

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#45]
from @rkikinis 

* See #44 
* Get images from discourse (e.g VMTK, New features for Segment Editor, ... )

**Comment by jcfr** [comment]
Here is the updated carousel:

![image](https://user-images.githubusercontent.com/219043/89836411-b59d7900-db34-11ea-8bb4-811ae94daba5.png)

@pieper @lassoan  Is there any particular image you suggest we use ? 

Looking at the list https://discourse.slicer.org/tag/feature, we should try to directly include youtube video
* [New module: Dynamic Modeler - parametric surface editing for biomedical applications](https://discourse.slicer.org/t/new-module-dynamic-modeler-parametric-surface-editing-for-biomedical-applications/11759)
* [AI-assisted segmentation extension](https://discourse.slicer.org/t/ai-assisted-segmentation-extension/9536)
* [How to make fiducial points placed in Curved Planar Reformatted image appear in the original image](https://discourse.slicer.org/t/how-to-make-fiducial-points-placed-in-curved-planar-reformatted-image-appear-in-the-original-image/12189/4?u=jcfr)


I am thinking about showcasing:
* transform module by making a collage of these images: https://www.slicer.org/wiki/Documentation/4.10/Modules/Transforms

**Comment by pieper** [comment]
Those look good Jc.  I think the carousel images should just be representative of the diversity, so anything that looks visually appealing and suggests the underlying power of the platform is good.

This SlicerRT image is nice, but only lo-res is on the site.  @lassoan, @cpinter is there a higher res version? http://slicerrt.github.io/images/SlicerRT_Montage.jpg

Same question for this SlicerIGT image: https://i1.wp.com/www.slicerigt.org/wp/wp-content/uploads/2014/03/SlicerIGT-Front-Applications.png

One of these could be good for SlicerCMF:
* https://pubmed.ncbi.nlm.nih.gov/31166412/#&gid=article-figures&pid=figure-4-uid-3
* https://pubmed.ncbi.nlm.nih.gov/31166412/#&gid=article-figures&pid=figure-2-uid-1

This looks good for SlicerCIP:
https://projects.iq.harvard.edu/sites/projects.iq.harvard.edu/files/styles/os_slideshow_16:9_980/public/chestimagingplatform/files/foto.png

Perhaps one of these for SlicerMorph
* https://blogs.uw.edu/maga/files/2017/04/VR-768x651.png
* https://slicermorph.github.io/images/09-Keep-selected-island.png

**Comment by jcfr** [comment]
Closing as @lassoan  already updated the Carousel in https://github.com/Slicer/slicer.org/pull/16/commits/003fc521e5562aa8d7cb51db2ebfd37b8c11e378

We will update existing or add new content incrementally.

**Comment by fedorov** [comment]
@pieper should we include a screenshot of one of those HTAN-like multichannel layouts you have?

**Comment by pieper** [comment]
> @pieper should we include a screenshot of one of those HTAN-like multichannel layouts you have?

I sent an email to the source of the image data to see if I can share it publicly and also what citation to provide.

**Comment by fedorov** [comment]
I thought about that public dataset from Sandro/Peter group - tonsil?

**Comment by pieper** [comment]
No, these particular ones were the TNP-Sardana (the original multichannel images that generated the jpegs used with Minerva Story on cycif.org).

**Comment by fedorov** [comment]
I thought way before Sardana, when you were experimenting with the Sorger tonsil data, you had something similar set up in Slicer, and also with multiview layout in OHIF, as a prototype. But I cannot find the references in the minutes, maybe it was in some email.

**Comment by pieper** [comment]
Yes, I did have those in Slicer but I didn't do the color channel blending, maybe just peudocolor.
