### ISSUE TITLE
Remove "Browser Extension" button

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#46]
Instead indicate that extension are available in Slicer

![image](https://user-images.githubusercontent.com/219043/89531702-a9c15800-d7be-11ea-9300-d1b5ef449127.png)

**Comment by lassoan** [comment]
Looks nice.

To reduce confusion, we should not use "Slicer" (but use "3D Slicer" or nothing) in headings. In longer text we could introduce the "Slicer" term (explain that it is just abbreviated form of 3D Slicer), but we could use other synonyms (application, platform, software,...) instead, so overall I would not use "Slicer" without "3D" on the main page.

**Comment by jcfr** [comment]
> reduce confusion, we should not use "Slicer" (but use "3D Slicer" or nothing)

This has been addressed

> Looks nice.

After the new extension manager is live, i think it could make sense to keep the "Browse Extensions" button ... in that case we will have to make display a "popup" indicating that extensions:
*  can be installed from within Slicer directly (preferred)
* or after downloading the archive and installing from file

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/Slicer/slicer.org/pull/16/commits/0d3289e7a811b7f496d453fb26908c30d87722bb associated with #16
