### ISSUE TITLE
Add SlicerMorph as a Solution

### ISSUE THREAD

**Issue by pieper** [Slicer/slicer.org#55]
here is the info needed to add into the solution section

> SlicerMorph enables biologists to retrieve, visualize, measure, segment and animate 3D biological specimens from digital collections of volumetric and surface scans. It also enables researchers to conduct landmark-based geometric morphometric analyses, all within the 3D Slicer.

https://slicermorph.github.io/

![image](https://user-images.githubusercontent.com/126077/89569326-90d29a00-d7f2-11ea-9ad6-885b4b951546.png)

**Comment by jcfr** [comment]
Square icon available here: https://github.com/SlicerMorph/SlicerMorph/blob/master/SlicerMorph_Color.png

**Comment by jcfr** [comment]
Preview on current website:

![image](https://user-images.githubusercontent.com/219043/89610074-a4f4b680-d847-11ea-862e-b158fb80f879.png)

**Comment by jcfr** [comment]
Preview on redesigned website:

![image](https://user-images.githubusercontent.com/219043/89610443-8347ff00-d848-11ea-9008-c339a099abfc.png)

I am wondering if there is a way to have a more condensed text. 

That said, it probably does not matter much consider we will soon address #54

**Comment by pieper** [comment]
🙏 !
