### ISSUE TITLE
Revisit presentation of features

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#57]
Reported by @rkikinis and @fedorov 

## Problem

Issues with the current approach:
* does not focus on the name of the feature. There are too much text around
* does not layout nicely because of text length difference. See #40 
* does not render nicely on mobile.

![image](https://user-images.githubusercontent.com/219043/89573509-b6fb3880-d7f8-11ea-912c-345ab6e3c32d.png)

## Proposed solution

* Use cards
* Show feature description in lighter color. For example:
* Or show the description in tooltip ?

## Examples

Source: https://bulma.io/documentation/
![image](https://user-images.githubusercontent.com/219043/89573142-27558a00-d7f8-11ea-8967-c5b2a78fb057.png)

Source: https://docs.amplify.aws/
![image](https://user-images.githubusercontent.com/219043/89573351-7c919b80-d7f8-11ea-835e-d1c76a4ef35e.png)

## Related

* https://github.com/Slicer/slicer.org/issues/19#issue-667972544
* https://github.com/Slicer/slicer.org/issues/40
* https://bulma.io/documentation/components/card/

**Comment by jcfr** [comment]
@lassoan @pieper 

Do you also think the current presentation of features could be improved ?

**Comment by pieper** [comment]
I like the cards idea - it loos better than the bullets.

**Comment by jcfr** [comment]
Closing. As of bb8a568500f370fc27d3fd5a09b685abe5bd6731, we have:



|Regular | Mobile |
|---|--|
| ![image](https://user-images.githubusercontent.com/219043/89835980-cac5d800-db33-11ea-91c9-c534849ae25f.png)| ![image](https://user-images.githubusercontent.com/219043/89835954-bda8e900-db33-11ea-90ad-98da584b88b2.png)|


cc: @pieper @lassoan
