### ISSUE TITLE
Fix spacing in About section 

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#58]
Add some space between  paragraph

![image](https://user-images.githubusercontent.com/219043/89689467-77088400-d8d2-11ea-86d3-3b99e66f7064.png)

**Comment by jcfr** [comment]
As of bb8a568500f370fc27d3fd5a09b685abe5bd6731:

![image](https://user-images.githubusercontent.com/219043/89834809-89ccc400-db31-11ea-9c80-536ebdc30f65.png)

@faiza-a Each sentence seems to be very close to each other ... I am wondering if anything could be  done to improve this.

**Comment by faiza-a** [comment]
changed spacing in ddab2a7
Let me know if this looks good to you or would like more spacing

**Comment by jcfr** [comment]
Before:
![image](https://user-images.githubusercontent.com/219043/89834809-89ccc400-db31-11ea-9c80-536ebdc30f65.png)

After:
![image](https://user-images.githubusercontent.com/219043/90688941-3d723a00-e23d-11ea-8568-5659e3c5f6ea.png)

> Let me know if this looks good to you or would like more spacing

Are we sure there is more space ?

**Comment by jcfr** [comment]
Lack of space is more problematic when looking at the side on mobile:

![image](https://user-images.githubusercontent.com/219043/90693539-04d65e80-e245-11ea-9c98-dcbd99af7e42.png)

**Comment by faiza-a** [comment]
<img width="1654" alt="Screen Shot 2020-08-24 at 12 41 41 PM" src="https://user-images.githubusercontent.com/61198087/91072273-3e251a80-e607-11ea-928f-2b077a57681b.png">
<img width="238" alt="Screen Shot 2020-08-24 at 12 41 52 PM" src="https://user-images.githubusercontent.com/61198087/91072328-54cb7180-e607-11ea-99d9-839028f64e8b.png">

I have set the line spacing to 2em in 665ac3e. if you would like to increase the spacing more we can change this value on line 225 in classes.sass file.
<img width="264" alt="Screen Shot 2020-08-24 at 12 44 38 PM" src="https://user-images.githubusercontent.com/61198087/91072527-a411a200-e607-11ea-8023-3b20f0180698.png">

**Comment by jcfr** [comment]
The spacing should be between each paragraph and not each  line.  Looking at it using the module version illustrate the problem:

![image](https://user-images.githubusercontent.com/219043/91175902-7c761480-e6af-11ea-8934-e9c7689c8253.png)

**Comment by jcfr** [comment]
Closing. This has been fixed in https://github.com/Slicer/slicer.org/pull/16
