### ISSUE TITLE
"Common questions" wrapped on two lines

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#6]
![slicer-org-common-question-wrapped](https://user-images.githubusercontent.com/219043/28170720-d3806428-67ab-11e7-8f61-6c37218e540e.png)

@ihnorton Could  you have a look ?

**Comment by freephile** [comment]
Maybe make the link text 'User FAQ' (like it is on the wiki) and also use a title attribute on the link "Common Questions" to provide a tooltip on hover.

**Comment by ihnorton** [comment]
Better?

![image](https://user-images.githubusercontent.com/327706/28175749-17bb316a-67c3-11e7-9f9b-9962d6386484.png)

https://github.com/Slicer/slicer.org/commit/72c53ed0e061b9d35a64517fbef988d264da5e17

Q&A seems more approachable than FAQ, but feel free to revert it if you want. The main point was to point to Discourse in the top bar.

**Comment by jcfr** [comment]
:+1:  Makes sense. 

For sake of consistency, could you also update the wiki ? and submit a PR on https://github.com/mhalle/slicer4-download/blob/master/slicer4DownloadServer/templates/download.html to change "Mailing list" to "Discussion Forum"

Closing. Fixed in https://github.com/Slicer/slicer.org/commit/72c53ed0e061b9d35a64517fbef988d264da5e17

**Comment by ihnorton** [comment]
I don't have Sidebar edit permission. Will try again tonight if someone has
a chance to grant access.

**Comment by jcfr** [comment]
@ihnorton I just added you to the groups "administrator", "bureaucrat", "editor" and "slicerWebAuthors". You should now be able to update the sidebar.
