### ISSUE TITLE
highlights on hero section buttons messed up returning to tab

### ISSUE THREAD

**Issue by pieper** [Slicer/slicer.org#61]
When you use the hero buttons a tab opens nicely, but when you close the tab the hover highlight is messed up.

The background color is still white at first, but then after you hover again the background and text are dark.

![image](https://user-images.githubusercontent.com/126077/89907691-fa6bf300-dbba-11ea-8f39-d397dc9f4a34.png)

![image](https://user-images.githubusercontent.com/126077/89907808-1e2f3900-dbbb-11ea-9655-ee426c9597a2.png)

**Comment by faiza-a** [comment]
fixed in 
25c6b53
