### ISSUE TITLE
Extension section is too dark

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#62]
![image](https://user-images.githubusercontent.com/219043/89909006-98ac8880-dbbc-11ea-8582-bfc5a260300a.png)

**Comment by faiza-a** [comment]
In commit 49b1237
Lightened it a little bit (from .8 to .6). Making it more lighter will make text hard to read.

<img width="1792" alt="Screen Shot 2020-08-17 at 4 54 28 PM" src="https://user-images.githubusercontent.com/61198087/90443669-9d84a700-e0aa-11ea-81fc-179da000a04d.png">

Darkness can be played around by changing the opacity value on line 241 in classes.sass file

<img width="432" alt="Screen Shot 2020-08-17 at 4 55 54 PM" src="https://user-images.githubusercontent.com/61198087/90443646-96f62f80-e0aa-11ea-8315-74c72f24845e.png">

**Comment by faiza-a** [comment]
I still think darker is looking better

**Comment by jcfr** [comment]
@lassoan @pieper  When you have chance, let us know what you think. In the mean time, I am closing.

Before:
![image](https://user-images.githubusercontent.com/219043/89909006-98ac8880-dbbc-11ea-8582-bfc5a260300a.png)

After:
![image](https://user-images.githubusercontent.com/219043/90687905-980a9680-e23b-11ea-8d29-099d3094c7aa.png)

**Comment by pieper** [comment]
How about an even lighter was and black text?  Would be nice if visitors could recognize the background as a bunch of app icons with Install buttons.

**Comment by lassoan** [comment]
I find darkening the background (kind of lime casting a strong shadow) is not appropriate here. It is usually used for temporarily hiding unrelated content. 

We should certainly reduce the contrast of the background image but not make it darker (it can be made brighter to bleach out the background to nearly white).
