### ISSUE TITLE
Fix listing of solution on index page

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#65]
Following https://github.com/Slicer/slicer.org/commit/7c290d9229dcf58f0db93b6c142bfddcf13fef43, solutions are extracted from a single source ([_data/solutions.yml](https://github.com/Slicer/slicer.org/blob/7c290d9229dcf58f0db93b6c142bfddcf13fef43/_data/solutions.yml))

Within the file, the solution are ordered, the problems seems to be that the current layout of solutions organizes each solutions by column instead of doing it by row.

Is there a way to address this ? 

The goal is to have solutions organized like **Before** based on the order in `_data/solutions.yml`

| Before | After |
|----|----|
| ![image](https://user-images.githubusercontent.com/219043/90791273-ff295900-e2d6-11ea-9e2e-438d1e8b8c38.png) | ![image](https://user-images.githubusercontent.com/219043/90791233-f20c6a00-e2d6-11ea-9459-c5e13261207b.png) |

**Comment by faiza-a** [comment]
I tried to do that. but if I use the row layout, there will be gaps between items. like this:
<img width="1036" alt="Screen Shot 2020-08-20 at 11 55 40 AM" src="https://user-images.githubusercontent.com/61198087/90795483-19b20100-e2dc-11ea-9ff9-f5f0339e2383.png">
i could find any other way.

Can we ask Brandon or Daniel Chiquito, if doing it across rows is possible without having gaps between items?

Other way would be to rearrange solutions in _data/solutions.yml

**Comment by lassoan** [comment]
It should be no problem to edit extension descriptions to have approximately the same length.

**Comment by faiza-a** [comment]
Yeah, still i think having this restriction of keeping the description to exactly three lines could be a problem in some cases.

Another option would be to completely remove the description and only keep logo, name and website link.

**Comment by jcfr** [comment]
I wrote some liquid template code last week to address this ... will push later in the afternoon and that should address this. 

The idea was to compute the col and row index to obtain the expected order.

**Comment by lassoan** [comment]
Solution names are not self-descriptive, so we need the text. It is not a problem to keep the teaser text short (visitors would not read longer text anyway).

**Comment by jcfr** [comment]
Waiting we revisit the teaser, I push a change fixing the order.
