### ISSUE TITLE
Favicon is very low quality

### ISSUE THREAD

**Issue by lassoan** [Slicer/slicer.org#73]
Compared to the old Slicer icon, Github icon, etc., the favicon of the reworked landing page is very low quality:

![image](https://user-images.githubusercontent.com/307929/111733811-1cafa880-884f-11eb-8ecc-454db79548ca.png)

Probably we should provide higher-resolution alternatives, not just a 16x16 icon (assets\img\3D-Slicer-Favicon.png).

**Comment by jamesobutler** [comment]
Inspecting the itk.org source on my desktop it was indicating a 192x192 icon and a 180x180 apple touch icon

```html
<link rel="icon" href="https://itk.org/wp-content/uploads/2019/11/cropped-ITK_Logo_512px-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon" href="https://itk.org/wp-content/uploads/2019/11/cropped-ITK_Logo_512px-180x180.png" />
```

**Comment by lassoan** [comment]
Yes, favicons were 16x16 about 25 years ago. Now the normal is over 100px - see for example here: https://www.emergeinteractive.com/insights/detail/The-Essentials-of-FavIcons/

**Comment by jcfr** [comment]
Last night I generated updated icons using https://realfavicongenerator.net/, I will submit a PR shortly.

The following will be added to the website:

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#1f65b0">
<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="theme-color" content="#1f65b0">
```


## Previews

![image](https://user-images.githubusercontent.com/219043/111801122-03d0e280-88a3-11eb-858b-8f986cd2002b.png)
![image](https://user-images.githubusercontent.com/219043/111801151-0a5f5a00-88a3-11eb-9788-88f79dd913e4.png)
![image](https://user-images.githubusercontent.com/219043/111801181-12b79500-88a3-11eb-93fb-41ded0426dd1.png)
![image](https://user-images.githubusercontent.com/219043/111801211-19dea300-88a3-11eb-814d-df3bce5b8970.png)
![image](https://user-images.githubusercontent.com/219043/111801251-2531ce80-88a3-11eb-9553-aa9729907dd0.png)

**Comment by lassoan** [comment]
Thanks a lot Jc, most of them look really good.

The macOS Safari looks funny, but I'm not sure it matters. Probably the black outline should be erased from the solid icon and that would make it look good.

The black background on iOS is not very appealing, but it works.

**Comment by jcfr** [comment]
> The macOS Safari looks funny, but I'm not sure it matters. Probably the black outline should be erased from the solid icon and that would make it look good.

A custom icon could be provided if it turns out to be an issue.

> The black background on iOS is not very appealing, but it works.

Agreed ... this could be tweaked also.

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/111847319-f46f8a80-88de-11eb-845d-39b9ba9e2205.png)

**Comment by jcfr** [comment]
File `assets/favicons/browserconfig.xml` contains `{{ site.baseurl }}` ... but it is not processed by the generator

**Comment by jcfr** [comment]
Remaining error:

![image](https://user-images.githubusercontent.com/219043/111848243-005c4c00-88e1-11eb-95af-c966cc794c49.png)

**Comment by jcfr** [comment]
Closing. This has been fixed.

**Comment by lassoan** [comment]
Thank you, the favicon is now very nice.
