### ISSUE TITLE
Fix generated twitter card

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#88]
![image](https://user-images.githubusercontent.com/219043/113191243-4becef00-922b-11eb-99c7-b0d0b92786f4.png)

**Comment by jamesobutler** [comment]
Need to define the OpenGraph and other Twitter specific meta properties in head.html
https://www.netlify.com/blog/2020/05/08/improve-your-seo-and-social-sharing-cards-with-next.js/?utm_source=twitter&utm_medium=-cs&utm_campaign=devex
```html
{/* Twitter */}
<meta name="twitter:card" content="summary" key="twcard" />
<meta name="twitter:creator" content={twitterHandle} key="twhandle" />

{/* Open Graph */}
<meta property="og:url" content={currentURL} key="ogurl" />
<meta property="og:image" content={previewImage} key="ogimage" />
<meta property="og:site_name" content={siteName} key="ogsitename" />
<meta property="og:title" content={pageTitle} key="ogtitle" />
<meta property="og:description" content={description} key="ogdesc" />
```

Can preview the tweet by using https://cards-dev.twitter.com/validator
![image](https://user-images.githubusercontent.com/15837524/113199314-fa496200-9234-11eb-8bc5-4f51b2f85fd6.png)

**Comment by jcfr** [comment]
After this last fix, we now have:

![image](https://user-images.githubusercontent.com/219043/113246290-c26b0a80-9286-11eb-9127-3d4376cbcca0.png)

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/113251110-b33c8a80-928f-11eb-8b22-85ec09ba1d4c.png)

**Comment by jcfr** [comment]
Rendering of image fixed in  https://github.com/Slicer/slicer.org/pull/92
